// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // Optional — only needed for `prisma migrate dev` in local development.
    // Not used by `migrate deploy` (production). `env()` throws when the
    // variable is unset, so read it directly to actually allow that.
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
